version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  docs_dir:
    docs

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: .mkdocs.yml

formats:
   - pdf
   - epub
