name: PyInstaller build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-pyinstaller-build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'release:') || startsWith(github.event.head_commit.message, 'build:')

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        python3.11 -m pip install pyinstaller WebtoonScraper

    - name: Build PyInstaller
      run: |
        pyinstaller -c pyinstaller.py

    - uses: actions/upload-artifact@v2
      with:
        name: linux-portable
        path: dist/pyinstaller

  windows-pyinstaller-build:
    runs-on: windows-latest
    if: startsWith(github.event.head_commit.message, 'release:') || startsWith(github.event.head_commit.message, 'build:')

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        py -3.11 -m pip install pyinstaller WebtoonScraper

    - name: Build PyInstaller
      run: |
        pyinstaller -c pyinstaller.py

    - uses: actions/upload-artifact@v2
      with:
        name: windows-portable
        path: dist/pyinstaller

  macos-pyinstaller-build:
    runs-on: macos-latest
    if: startsWith(github.event.head_commit.message, 'release:') || startsWith(github.event.head_commit.message, 'build:')

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        python3.11 -m pip install pyinstaller WebtoonScraper
  
    - name: Build PyInstaller
      run: |
        pyinstaller -c pyinstaller.py

    - uses: actions/upload-artifact@v2
      with:
        name: macos-portable
        path: dist/pyinstaller
